/**
 */
package edu.uoc.som.dsl4ai.provider;

import edu.uoc.som.dsl4ai.util.Dsl4aiAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class Dsl4aiItemProviderAdapterFactory extends Dsl4aiAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Dsl4aiItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Activity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivityItemProvider activityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Activity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActivityAdapter() {
		if (activityItemProvider == null) {
			activityItemProvider = new ActivityItemProvider(this);
		}

		return activityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Document} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentItemProvider documentItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Document}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentAdapter() {
		if (documentItemProvider == null) {
			documentItemProvider = new DocumentItemProvider(this);
		}

		return documentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Template} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TemplateItemProvider templateItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Template}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTemplateAdapter() {
		if (templateItemProvider == null) {
			templateItemProvider = new TemplateItemProvider(this);
		}

		return templateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Platform} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlatformItemProvider platformItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Platform}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlatformAdapter() {
		if (platformItemProvider == null) {
			platformItemProvider = new PlatformItemProvider(this);
		}

		return platformItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Script} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScriptItemProvider scriptItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Script}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScriptAdapter() {
		if (scriptItemProvider == null) {
			scriptItemProvider = new ScriptItemProvider(this);
		}

		return scriptItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Guideline} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GuidelineItemProvider guidelineItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Guideline}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGuidelineAdapter() {
		if (guidelineItemProvider == null) {
			guidelineItemProvider = new GuidelineItemProvider(this);
		}

		return guidelineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Participant} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParticipantItemProvider participantItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Participant}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParticipantAdapter() {
		if (participantItemProvider == null) {
			participantItemProvider = new ParticipantItemProvider(this);
		}

		return participantItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.BusinessUnderstandingActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BusinessUnderstandingActivityItemProvider businessUnderstandingActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.BusinessUnderstandingActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBusinessUnderstandingActivityAdapter() {
		if (businessUnderstandingActivityItemProvider == null) {
			businessUnderstandingActivityItemProvider = new BusinessUnderstandingActivityItemProvider(this);
		}

		return businessUnderstandingActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.RequirementsEngineeringActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequirementsEngineeringActivityItemProvider requirementsEngineeringActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.RequirementsEngineeringActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequirementsEngineeringActivityAdapter() {
		if (requirementsEngineeringActivityItemProvider == null) {
			requirementsEngineeringActivityItemProvider = new RequirementsEngineeringActivityItemProvider(this);
		}

		return requirementsEngineeringActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataIdentificationActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataIdentificationActivityItemProvider dataIdentificationActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataIdentificationActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataIdentificationActivityAdapter() {
		if (dataIdentificationActivityItemProvider == null) {
			dataIdentificationActivityItemProvider = new DataIdentificationActivityItemProvider(this);
		}

		return dataIdentificationActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Requirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequirementItemProvider requirementItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Requirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequirementAdapter() {
		if (requirementItemProvider == null) {
			requirementItemProvider = new RequirementItemProvider(this);
		}

		return requirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelRequirementItemProvider aiModelRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelRequirementAdapter() {
		if (aiModelRequirementItemProvider == null) {
			aiModelRequirementItemProvider = new AIModelRequirementItemProvider(this);
		}

		return aiModelRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.BusinessGoal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BusinessGoalItemProvider businessGoalItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.BusinessGoal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBusinessGoalAdapter() {
		if (businessGoalItemProvider == null) {
			businessGoalItemProvider = new BusinessGoalItemProvider(this);
		}

		return businessGoalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelGoal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelGoalItemProvider aiModelGoalItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelGoal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelGoalAdapter() {
		if (aiModelGoalItemProvider == null) {
			aiModelGoalItemProvider = new AIModelGoalItemProvider(this);
		}

		return aiModelGoalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.BusinessSuccessCriterion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BusinessSuccessCriterionItemProvider businessSuccessCriterionItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.BusinessSuccessCriterion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBusinessSuccessCriterionAdapter() {
		if (businessSuccessCriterionItemProvider == null) {
			businessSuccessCriterionItemProvider = new BusinessSuccessCriterionItemProvider(this);
		}

		return businessSuccessCriterionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelSuccessCriterion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelSuccessCriterionItemProvider aiModelSuccessCriterionItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelSuccessCriterion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelSuccessCriterionAdapter() {
		if (aiModelSuccessCriterionItemProvider == null) {
			aiModelSuccessCriterionItemProvider = new AIModelSuccessCriterionItemProvider(this);
		}

		return aiModelSuccessCriterionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataSource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataSourceItemProvider dataSourceItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataSource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataSourceAdapter() {
		if (dataSourceItemProvider == null) {
			dataSourceItemProvider = new DataSourceItemProvider(this);
		}

		return dataSourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataSourceRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataSourceRequirementItemProvider dataSourceRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataSourceRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataSourceRequirementAdapter() {
		if (dataSourceRequirementItemProvider == null) {
			dataSourceRequirementItemProvider = new DataSourceRequirementItemProvider(this);
		}

		return dataSourceRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataRequirementItemProvider dataRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataRequirementAdapter() {
		if (dataRequirementItemProvider == null) {
			dataRequirementItemProvider = new DataRequirementItemProvider(this);
		}

		return dataRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIEthicalRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIEthicalRequirementItemProvider aiEthicalRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIEthicalRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIEthicalRequirementAdapter() {
		if (aiEthicalRequirementItemProvider == null) {
			aiEthicalRequirementItemProvider = new AIEthicalRequirementItemProvider(this);
		}

		return aiEthicalRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelDegradation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelDegradationItemProvider aiModelDegradationItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelDegradation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelDegradationAdapter() {
		if (aiModelDegradationItemProvider == null) {
			aiModelDegradationItemProvider = new AIModelDegradationItemProvider(this);
		}

		return aiModelDegradationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Method} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MethodItemProvider methodItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Method}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMethodAdapter() {
		if (methodItemProvider == null) {
			methodItemProvider = new MethodItemProvider(this);
		}

		return methodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataPreparationActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataPreparationActivityItemProvider dataPreparationActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataPreparationActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataPreparationActivityAdapter() {
		if (dataPreparationActivityItemProvider == null) {
			dataPreparationActivityItemProvider = new DataPreparationActivityItemProvider(this);
		}

		return dataPreparationActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataCollectionActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataCollectionActivityItemProvider dataCollectionActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataCollectionActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataCollectionActivityAdapter() {
		if (dataCollectionActivityItemProvider == null) {
			dataCollectionActivityItemProvider = new DataCollectionActivityItemProvider(this);
		}

		return dataCollectionActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataProcessingActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataProcessingActivityItemProvider dataProcessingActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataProcessingActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataProcessingActivityAdapter() {
		if (dataProcessingActivityItemProvider == null) {
			dataProcessingActivityItemProvider = new DataProcessingActivityItemProvider(this);
		}

		return dataProcessingActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataAnnotationGuideline} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataAnnotationGuidelineItemProvider dataAnnotationGuidelineItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataAnnotationGuideline}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataAnnotationGuidelineAdapter() {
		if (dataAnnotationGuidelineItemProvider == null) {
			dataAnnotationGuidelineItemProvider = new DataAnnotationGuidelineItemProvider(this);
		}

		return dataAnnotationGuidelineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Label} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LabelItemProvider labelItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Label}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLabelAdapter() {
		if (labelItemProvider == null) {
			labelItemProvider = new LabelItemProvider(this);
		}

		return labelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Data} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataItemProvider dataItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Data}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataAdapter() {
		if (dataItemProvider == null) {
			dataItemProvider = new DataItemProvider(this);
		}

		return dataItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.FeatureEngineeringActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureEngineeringActivityItemProvider featureEngineeringActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.FeatureEngineeringActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureEngineeringActivityAdapter() {
		if (featureEngineeringActivityItemProvider == null) {
			featureEngineeringActivityItemProvider = new FeatureEngineeringActivityItemProvider(this);
		}

		return featureEngineeringActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Feature} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureItemProvider featureItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Feature}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureAdapter() {
		if (featureItemProvider == null) {
			featureItemProvider = new FeatureItemProvider(this);
		}

		return featureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataAttributeItemProvider dataAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataAttributeAdapter() {
		if (dataAttributeItemProvider == null) {
			dataAttributeItemProvider = new DataAttributeItemProvider(this);
		}

		return dataAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelingActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelingActivityItemProvider aiModelingActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelingActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelingActivityAdapter() {
		if (aiModelingActivityItemProvider == null) {
			aiModelingActivityItemProvider = new AIModelingActivityItemProvider(this);
		}

		return aiModelingActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelTrainingActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelTrainingActivityItemProvider aiModelTrainingActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelTrainingActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelTrainingActivityAdapter() {
		if (aiModelTrainingActivityItemProvider == null) {
			aiModelTrainingActivityItemProvider = new AIModelTrainingActivityItemProvider(this);
		}

		return aiModelTrainingActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelEvaluationActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelEvaluationActivityItemProvider aiModelEvaluationActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelEvaluationActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelEvaluationActivityAdapter() {
		if (aiModelEvaluationActivityItemProvider == null) {
			aiModelEvaluationActivityItemProvider = new AIModelEvaluationActivityItemProvider(this);
		}

		return aiModelEvaluationActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.TrainingDataset} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TrainingDatasetItemProvider trainingDatasetItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.TrainingDataset}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTrainingDatasetAdapter() {
		if (trainingDatasetItemProvider == null) {
			trainingDatasetItemProvider = new TrainingDatasetItemProvider(this);
		}

		return trainingDatasetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.ValidationDataset} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValidationDatasetItemProvider validationDatasetItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.ValidationDataset}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValidationDatasetAdapter() {
		if (validationDatasetItemProvider == null) {
			validationDatasetItemProvider = new ValidationDatasetItemProvider(this);
		}

		return validationDatasetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.TestDataset} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TestDatasetItemProvider testDatasetItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.TestDataset}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTestDatasetAdapter() {
		if (testDatasetItemProvider == null) {
			testDatasetItemProvider = new TestDatasetItemProvider(this);
		}

		return testDatasetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelItemProvider aiModelItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelAdapter() {
		if (aiModelItemProvider == null) {
			aiModelItemProvider = new AIModelItemProvider(this);
		}

		return aiModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.CriterionValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CriterionValueItemProvider criterionValueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.CriterionValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCriterionValueAdapter() {
		if (criterionValueItemProvider == null) {
			criterionValueItemProvider = new CriterionValueItemProvider(this);
		}

		return criterionValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.HyperParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HyperParameterItemProvider hyperParameterItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.HyperParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHyperParameterAdapter() {
		if (hyperParameterItemProvider == null) {
			hyperParameterItemProvider = new HyperParameterItemProvider(this);
		}

		return hyperParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.OptimalValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OptimalValueItemProvider optimalValueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.OptimalValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOptimalValueAdapter() {
		if (optimalValueItemProvider == null) {
			optimalValueItemProvider = new OptimalValueItemProvider(this);
		}

		return optimalValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelDataset} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelDatasetItemProvider aiModelDatasetItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelDataset}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelDatasetAdapter() {
		if (aiModelDatasetItemProvider == null) {
			aiModelDatasetItemProvider = new AIModelDatasetItemProvider(this);
		}

		return aiModelDatasetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.OperationsActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OperationsActivityItemProvider operationsActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.OperationsActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOperationsActivityAdapter() {
		if (operationsActivityItemProvider == null) {
			operationsActivityItemProvider = new OperationsActivityItemProvider(this);
		}

		return operationsActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelDeploymentActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelDeploymentActivityItemProvider aiModelDeploymentActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelDeploymentActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelDeploymentActivityAdapter() {
		if (aiModelDeploymentActivityItemProvider == null) {
			aiModelDeploymentActivityItemProvider = new AIModelDeploymentActivityItemProvider(this);
		}

		return aiModelDeploymentActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelMonitoringActivity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelMonitoringActivityItemProvider aiModelMonitoringActivityItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelMonitoringActivity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelMonitoringActivityAdapter() {
		if (aiModelMonitoringActivityItemProvider == null) {
			aiModelMonitoringActivityItemProvider = new AIModelMonitoringActivityItemProvider(this);
		}

		return aiModelMonitoringActivityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DeployedAIModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeployedAIModelItemProvider deployedAIModelItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DeployedAIModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeployedAIModelAdapter() {
		if (deployedAIModelItemProvider == null) {
			deployedAIModelItemProvider = new DeployedAIModelItemProvider(this);
		}

		return deployedAIModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Issue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IssueItemProvider issueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Issue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIssueAdapter() {
		if (issueItemProvider == null) {
			issueItemProvider = new IssueItemProvider(this);
		}

		return issueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.AIModelFlaw} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AIModelFlawItemProvider aiModelFlawItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.AIModelFlaw}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAIModelFlawAdapter() {
		if (aiModelFlawItemProvider == null) {
			aiModelFlawItemProvider = new AIModelFlawItemProvider(this);
		}

		return aiModelFlawItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.PerformanceMetric} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PerformanceMetricItemProvider performanceMetricItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.PerformanceMetric}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPerformanceMetricAdapter() {
		if (performanceMetricItemProvider == null) {
			performanceMetricItemProvider = new PerformanceMetricItemProvider(this);
		}

		return performanceMetricItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataCleaningTechnique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataCleaningTechniqueItemProvider dataCleaningTechniqueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataCleaningTechnique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataCleaningTechniqueAdapter() {
		if (dataCleaningTechniqueItemProvider == null) {
			dataCleaningTechniqueItemProvider = new DataCleaningTechniqueItemProvider(this);
		}

		return dataCleaningTechniqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataTransformationTechnique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataTransformationTechniqueItemProvider dataTransformationTechniqueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataTransformationTechnique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataTransformationTechniqueAdapter() {
		if (dataTransformationTechniqueItemProvider == null) {
			dataTransformationTechniqueItemProvider = new DataTransformationTechniqueItemProvider(this);
		}

		return dataTransformationTechniqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataDiscretizationTechnique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataDiscretizationTechniqueItemProvider dataDiscretizationTechniqueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataDiscretizationTechnique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataDiscretizationTechniqueAdapter() {
		if (dataDiscretizationTechniqueItemProvider == null) {
			dataDiscretizationTechniqueItemProvider = new DataDiscretizationTechniqueItemProvider(this);
		}

		return dataDiscretizationTechniqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataReductionTechnique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataReductionTechniqueItemProvider dataReductionTechniqueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataReductionTechnique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataReductionTechniqueAdapter() {
		if (dataReductionTechniqueItemProvider == null) {
			dataReductionTechniqueItemProvider = new DataReductionTechniqueItemProvider(this);
		}

		return dataReductionTechniqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataIntegrationTechnique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataIntegrationTechniqueItemProvider dataIntegrationTechniqueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataIntegrationTechnique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataIntegrationTechniqueAdapter() {
		if (dataIntegrationTechniqueItemProvider == null) {
			dataIntegrationTechniqueItemProvider = new DataIntegrationTechniqueItemProvider(this);
		}

		return dataIntegrationTechniqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataAugmentationTechnique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataAugmentationTechniqueItemProvider dataAugmentationTechniqueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataAugmentationTechnique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataAugmentationTechniqueAdapter() {
		if (dataAugmentationTechniqueItemProvider == null) {
			dataAugmentationTechniqueItemProvider = new DataAugmentationTechniqueItemProvider(this);
		}

		return dataAugmentationTechniqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.FeatureExtractionTechnique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureExtractionTechniqueItemProvider featureExtractionTechniqueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.FeatureExtractionTechnique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureExtractionTechniqueAdapter() {
		if (featureExtractionTechniqueItemProvider == null) {
			featureExtractionTechniqueItemProvider = new FeatureExtractionTechniqueItemProvider(this);
		}

		return featureExtractionTechniqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.FeatureSelectionTechnique} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureSelectionTechniqueItemProvider featureSelectionTechniqueItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.FeatureSelectionTechnique}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureSelectionTechniqueAdapter() {
		if (featureSelectionTechniqueItemProvider == null) {
			featureSelectionTechniqueItemProvider = new FeatureSelectionTechniqueItemProvider(this);
		}

		return featureSelectionTechniqueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.GroupManager} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GroupManagerItemProvider groupManagerItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.GroupManager}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGroupManagerAdapter() {
		if (groupManagerItemProvider == null) {
			groupManagerItemProvider = new GroupManagerItemProvider(this);
		}

		return groupManagerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.TeamLead} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TeamLeadItemProvider teamLeadItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.TeamLead}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTeamLeadAdapter() {
		if (teamLeadItemProvider == null) {
			teamLeadItemProvider = new TeamLeadItemProvider(this);
		}

		return teamLeadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.ProjectLead} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProjectLeadItemProvider projectLeadItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.ProjectLead}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProjectLeadAdapter() {
		if (projectLeadItemProvider == null) {
			projectLeadItemProvider = new ProjectLeadItemProvider(this);
		}

		return projectLeadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataConsumer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataConsumerItemProvider dataConsumerItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataConsumer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataConsumerAdapter() {
		if (dataConsumerItemProvider == null) {
			dataConsumerItemProvider = new DataConsumerItemProvider(this);
		}

		return dataConsumerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.BusinessUser} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BusinessUserItemProvider businessUserItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.BusinessUser}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBusinessUserAdapter() {
		if (businessUserItemProvider == null) {
			businessUserItemProvider = new BusinessUserItemProvider(this);
		}

		return businessUserItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.BusinessAnalyst} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BusinessAnalystItemProvider businessAnalystItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.BusinessAnalyst}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBusinessAnalystAdapter() {
		if (businessAnalystItemProvider == null) {
			businessAnalystItemProvider = new BusinessAnalystItemProvider(this);
		}

		return businessAnalystItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DomainExpert} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainExpertItemProvider domainExpertItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DomainExpert}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainExpertAdapter() {
		if (domainExpertItemProvider == null) {
			domainExpertItemProvider = new DomainExpertItemProvider(this);
		}

		return domainExpertItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataScientist} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataScientistItemProvider dataScientistItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataScientist}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataScientistAdapter() {
		if (dataScientistItemProvider == null) {
			dataScientistItemProvider = new DataScientistItemProvider(this);
		}

		return dataScientistItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataEngineer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataEngineerItemProvider dataEngineerItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataEngineer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataEngineerAdapter() {
		if (dataEngineerItemProvider == null) {
			dataEngineerItemProvider = new DataEngineerItemProvider(this);
		}

		return dataEngineerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataSteward} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataStewardItemProvider dataStewardItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataSteward}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataStewardAdapter() {
		if (dataStewardItemProvider == null) {
			dataStewardItemProvider = new DataStewardItemProvider(this);
		}

		return dataStewardItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataProvider} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataProviderItemProvider dataProviderItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataProvider}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataProviderAdapter() {
		if (dataProviderItemProvider == null) {
			dataProviderItemProvider = new DataProviderItemProvider(this);
		}

		return dataProviderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.DataAnnotator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataAnnotatorItemProvider dataAnnotatorItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.DataAnnotator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataAnnotatorAdapter() {
		if (dataAnnotatorItemProvider == null) {
			dataAnnotatorItemProvider = new DataAnnotatorItemProvider(this);
		}

		return dataAnnotatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.Architect} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArchitectItemProvider architectItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.Architect}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArchitectAdapter() {
		if (architectItemProvider == null) {
			architectItemProvider = new ArchitectItemProvider(this);
		}

		return architectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.SoftwareEngineer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SoftwareEngineerItemProvider softwareEngineerItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.SoftwareEngineer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSoftwareEngineerAdapter() {
		if (softwareEngineerItemProvider == null) {
			softwareEngineerItemProvider = new SoftwareEngineerItemProvider(this);
		}

		return softwareEngineerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link edu.uoc.som.dsl4ai.ModelOperator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelOperatorItemProvider modelOperatorItemProvider;

	/**
	 * This creates an adapter for a {@link edu.uoc.som.dsl4ai.ModelOperator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelOperatorAdapter() {
		if (modelOperatorItemProvider == null) {
			modelOperatorItemProvider = new ModelOperatorItemProvider(this);
		}

		return modelOperatorItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (activityItemProvider != null)
			activityItemProvider.dispose();
		if (documentItemProvider != null)
			documentItemProvider.dispose();
		if (templateItemProvider != null)
			templateItemProvider.dispose();
		if (platformItemProvider != null)
			platformItemProvider.dispose();
		if (scriptItemProvider != null)
			scriptItemProvider.dispose();
		if (guidelineItemProvider != null)
			guidelineItemProvider.dispose();
		if (participantItemProvider != null)
			participantItemProvider.dispose();
		if (businessUnderstandingActivityItemProvider != null)
			businessUnderstandingActivityItemProvider.dispose();
		if (requirementsEngineeringActivityItemProvider != null)
			requirementsEngineeringActivityItemProvider.dispose();
		if (dataIdentificationActivityItemProvider != null)
			dataIdentificationActivityItemProvider.dispose();
		if (requirementItemProvider != null)
			requirementItemProvider.dispose();
		if (aiModelRequirementItemProvider != null)
			aiModelRequirementItemProvider.dispose();
		if (businessGoalItemProvider != null)
			businessGoalItemProvider.dispose();
		if (aiModelGoalItemProvider != null)
			aiModelGoalItemProvider.dispose();
		if (businessSuccessCriterionItemProvider != null)
			businessSuccessCriterionItemProvider.dispose();
		if (aiModelSuccessCriterionItemProvider != null)
			aiModelSuccessCriterionItemProvider.dispose();
		if (dataSourceItemProvider != null)
			dataSourceItemProvider.dispose();
		if (dataSourceRequirementItemProvider != null)
			dataSourceRequirementItemProvider.dispose();
		if (dataRequirementItemProvider != null)
			dataRequirementItemProvider.dispose();
		if (aiEthicalRequirementItemProvider != null)
			aiEthicalRequirementItemProvider.dispose();
		if (aiModelDegradationItemProvider != null)
			aiModelDegradationItemProvider.dispose();
		if (methodItemProvider != null)
			methodItemProvider.dispose();
		if (dataPreparationActivityItemProvider != null)
			dataPreparationActivityItemProvider.dispose();
		if (dataCollectionActivityItemProvider != null)
			dataCollectionActivityItemProvider.dispose();
		if (dataProcessingActivityItemProvider != null)
			dataProcessingActivityItemProvider.dispose();
		if (dataAnnotationGuidelineItemProvider != null)
			dataAnnotationGuidelineItemProvider.dispose();
		if (labelItemProvider != null)
			labelItemProvider.dispose();
		if (dataItemProvider != null)
			dataItemProvider.dispose();
		if (featureEngineeringActivityItemProvider != null)
			featureEngineeringActivityItemProvider.dispose();
		if (featureItemProvider != null)
			featureItemProvider.dispose();
		if (dataAttributeItemProvider != null)
			dataAttributeItemProvider.dispose();
		if (aiModelingActivityItemProvider != null)
			aiModelingActivityItemProvider.dispose();
		if (aiModelTrainingActivityItemProvider != null)
			aiModelTrainingActivityItemProvider.dispose();
		if (aiModelEvaluationActivityItemProvider != null)
			aiModelEvaluationActivityItemProvider.dispose();
		if (trainingDatasetItemProvider != null)
			trainingDatasetItemProvider.dispose();
		if (validationDatasetItemProvider != null)
			validationDatasetItemProvider.dispose();
		if (testDatasetItemProvider != null)
			testDatasetItemProvider.dispose();
		if (aiModelItemProvider != null)
			aiModelItemProvider.dispose();
		if (criterionValueItemProvider != null)
			criterionValueItemProvider.dispose();
		if (hyperParameterItemProvider != null)
			hyperParameterItemProvider.dispose();
		if (optimalValueItemProvider != null)
			optimalValueItemProvider.dispose();
		if (aiModelDatasetItemProvider != null)
			aiModelDatasetItemProvider.dispose();
		if (operationsActivityItemProvider != null)
			operationsActivityItemProvider.dispose();
		if (aiModelDeploymentActivityItemProvider != null)
			aiModelDeploymentActivityItemProvider.dispose();
		if (aiModelMonitoringActivityItemProvider != null)
			aiModelMonitoringActivityItemProvider.dispose();
		if (deployedAIModelItemProvider != null)
			deployedAIModelItemProvider.dispose();
		if (issueItemProvider != null)
			issueItemProvider.dispose();
		if (aiModelFlawItemProvider != null)
			aiModelFlawItemProvider.dispose();
		if (performanceMetricItemProvider != null)
			performanceMetricItemProvider.dispose();
		if (dataCleaningTechniqueItemProvider != null)
			dataCleaningTechniqueItemProvider.dispose();
		if (dataTransformationTechniqueItemProvider != null)
			dataTransformationTechniqueItemProvider.dispose();
		if (dataDiscretizationTechniqueItemProvider != null)
			dataDiscretizationTechniqueItemProvider.dispose();
		if (dataReductionTechniqueItemProvider != null)
			dataReductionTechniqueItemProvider.dispose();
		if (dataIntegrationTechniqueItemProvider != null)
			dataIntegrationTechniqueItemProvider.dispose();
		if (dataAugmentationTechniqueItemProvider != null)
			dataAugmentationTechniqueItemProvider.dispose();
		if (featureExtractionTechniqueItemProvider != null)
			featureExtractionTechniqueItemProvider.dispose();
		if (featureSelectionTechniqueItemProvider != null)
			featureSelectionTechniqueItemProvider.dispose();
		if (groupManagerItemProvider != null)
			groupManagerItemProvider.dispose();
		if (teamLeadItemProvider != null)
			teamLeadItemProvider.dispose();
		if (projectLeadItemProvider != null)
			projectLeadItemProvider.dispose();
		if (dataConsumerItemProvider != null)
			dataConsumerItemProvider.dispose();
		if (businessUserItemProvider != null)
			businessUserItemProvider.dispose();
		if (businessAnalystItemProvider != null)
			businessAnalystItemProvider.dispose();
		if (domainExpertItemProvider != null)
			domainExpertItemProvider.dispose();
		if (dataScientistItemProvider != null)
			dataScientistItemProvider.dispose();
		if (dataEngineerItemProvider != null)
			dataEngineerItemProvider.dispose();
		if (dataStewardItemProvider != null)
			dataStewardItemProvider.dispose();
		if (dataProviderItemProvider != null)
			dataProviderItemProvider.dispose();
		if (dataAnnotatorItemProvider != null)
			dataAnnotatorItemProvider.dispose();
		if (architectItemProvider != null)
			architectItemProvider.dispose();
		if (softwareEngineerItemProvider != null)
			softwareEngineerItemProvider.dispose();
		if (modelOperatorItemProvider != null)
			modelOperatorItemProvider.dispose();
	}

}
